<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1658299966012' stop='1658299994586'>
    <name>Verify user able to  cancel admission only once </name>
    <title>Verify user able to  cancel admission only once </title>
    <test-cases>
        <test-case start='1658299966013' status='failed' stop='1658299994586'>
            <name>cancel admission  can be performed only once</name>
            <title>cancel admission  can be performed only once</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-101.0.4951.54'/>
                <parameter kind='argument' name='browser' value='chrome-101.0.4951.54'/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='2e187275-771f-45b2-b3b5-0ae30b2fe52d-attachment.png' type='image/png' size='95951'/>
            </attachments>
            <failure>
                <message>expected 'coursenametobecancelled' to not exist      
                      actual expected
                      
                      'coursenametobecancelled'undefined
                      </message>
                <stack-trace>AssertionError: expected 'coursenametobecancelled' to not exist
                    at Context.&lt;anonymous> (/home/vaibhav/Desktop/demoproject/Alis/test/Students/Verifyuserabletocanceladmissiononlyonce.js:51:58)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>